#############
# DEPLOYMENT  
#############
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: web-d
spec:
  selector:   #permite seleccionar un conjunto de objetos que cumplan las condicione
    matchLabels:
      app: web
  replicas: 2 # indica al controlador que ejecute 2 pods
  template:   # Plantilla que define los containers
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: apache
        image: apasoft/web:latest
        ports:
        - containerPort: 80
---
# para hacer un split de yml se utilizan ---
#############
# SERVICIO  
#############
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
     app: web
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
     app: web 
# apunta al label correspondiente  recursos de tipo pod o deployment, en este caso app: web se ebcuebntra en el deployment (por medio de matchLabels) y en el pod (por medio de labels) 
# y se pueden tomar en cuenta ambos para la creacion del servicio
